#!/bin/sh
#
# Build the PS2VMC WebAssembly module.
#
# Requires Emscripten (https://emscripten.org):
#     brew install emscripten          # macOS
#     apt install emscripten           # Debian/Ubuntu
#
# The output (ps2vmc-wasm.js + ps2vmc-wasm.wasm) is checked into the repository,
# so you only need to run this after changing src/mcio.c, src/util.c,
# src/ps2save.c or src/web_api.c.
#
# Note: emscripten's SINGLE_FILE is deliberately NOT used. It embeds the module
# as a JS string literal of RAW BINARY (not base64), leaving thousands of NUL
# and high bytes inside a .js file. Instead this script compiles to a separate
# .wasm and then base64-encodes it into ps2vmc-wasm-binary.js, which:
#   * keeps every shipped file plain ASCII, and
#   * needs no fetch() at run time, so the page also works from a file:// URL.
#
set -e

cd "$(dirname "$0")"
ROOT=..
OUT=ps2vmc-wasm.js

# -Oz, not -O3: it takes the module from 123 KB to 101 KB (164 KB to 134 KB
# once base64'd), which helps however the page is delivered. The cost is about
# 12% on LZARI encoding - a .max export of a whole card goes from ~47 ms to
# ~52 ms - and nothing measurable on the zlib paths.
#
# Compressing the module before the base64 was considered and is not worth it:
# any server that content-encodes already sends the plain base64 smaller than a
# pre-compressed copy would be, and doing it ourselves would need an async
# DecompressionStream step on a page that currently needs none.
emcc \
	-Oz \
	-I "$ROOT/include" -I "$ROOT" \
	"$ROOT/src/mcio.c" \
	"$ROOT/src/util.c" \
	"$ROOT/src/ps2save.c" \
	"$ROOT/src/ps2blank.c" \
	"$ROOT/src/lzari.c" \
	src/web_api.c \
	-o "$OUT" \
	--no-entry \
	-s USE_ZLIB=1 \
	-s MODULARIZE=1 \
	-s EXPORT_NAME=createPS2VMC \
	-s EXPORT_ES6=0 \
	-s ALLOW_MEMORY_GROWTH=1 \
	-s INITIAL_MEMORY=64MB \
	-s EXPORTED_FUNCTIONS=_malloc,_free \
	-s INCOMING_MODULE_JS_API=wasmBinary \
	-s EXPORTED_RUNTIME_METHODS=ccall,cwrap,UTF8ToString,stringToUTF8,lengthBytesUTF8,HEAPU8,HEAP32 \
	-s FILESYSTEM=0 \
	-s ENVIRONMENT=web,node \
	-s STRICT=1 \
	--closure 0

WASM="${OUT%.js}.wasm"
B64="${OUT%.js}-binary.js"

# Wrap the module as base64 in a script that works as a browser global and as a
# CommonJS module, so no fetch is needed and every shipped file stays ASCII.
{
	printf '/* Generated by build.sh - do not edit. %s as base64. */\n' "$(basename "$WASM")"
	printf '(function(root,factory){if(typeof module==="object"&&module.exports)module.exports=factory();'
	printf 'else root.PS2VMC_WASM_BASE64=factory();})(typeof self!=="undefined"?self:this,function(){return"'
	base64 < "$WASM" | tr -d '\n'
	printf '"});\n'
} > "$B64"

rm -f "$WASM"

echo "built $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes, ASCII glue)"
echo "built $B64 ($(wc -c < "$B64" | tr -d ' ') bytes, ASCII base64 module)"
